### PR TITLE
Check in test data

### PR DESCRIPTION
**Pull request by candrews-thrive**
Add user for testing CheckIn

### CODE REVIEW

**Comment by hookom** [comment]
Don't we need the corresponding teardown script(s) to accompany these creates?

**Comment by candrews-thrive** [comment]
The data will get deleted with TearDownUsers script

**Comment by hookom** [comment]
Do our teardown scripts account for inserts like this one:
INSERT INTO [dbo].dp_user_roles 
 (User_ID,Role_ID,Domain_ID) VALUES
 (@userId,112      ,1        );

They may, I just can't remember if we delete from the dp_user_roles table.

**Comment by candrews-thrive** [comment]
I believe so I copy that code from KathrynCradduckTest.sql . I look and there is nothing in the tear down folder for that script.

**Pull request merged**
