### PR TITLE
Feature/us1100 move style guide

### PR DESCRIPTION
**Pull request by saylormic**

### CODE REVIEW

**Comment by tatelucas** [comment]
Can you remove the webkit blue outline on the active buttons? See screencap: https://www.evernote.com/shard/s45/sh/10a3fd93-c532-4f82-8427-c920b7856f3d/70bf21d0be2c63563bc9aee24ae96023

-Add "If it's all the same to you...." alert to credit card section

-Button fonts are not right for me. Trying to reference Roboto it's not there? Is the Google font included correctly?

**Comment by tatelucas** [comment]
Remove jekyll raw tags. eg. {% raw %} HIDE {% endraw %}
Growl alerts don't work
Layout links dont work. Put a note that they dont exist in new repo

**Comment by saylormic** [comment]
Removed jekyll raw tags

**Comment by saylormic** [comment]
Removed layout links, and put in note about not working in current repo.

**Comment by saylormic** [comment]
Fixed growl messages

**Pull request merged**
